<!doctype html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
		  content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="/css/bootstrap/bootstrap-grid.min.css">
	<link rel="stylesheet" href="/css/bootstrap/bootstrap-reboot.css">
	<link rel="stylesheet" href="/css/style.css">

	<script src="/js/JQery.js"></script>
	<script src="/js/bootstrap/bootstrap.bundle.js"></script>
	<script src="/js/main.js"></script>
	<title><?=$pageTitle?></title>
	<? if (!empty($pageKeywords)):?>
		<meta name="keywords" content="<?=$pageKeywords?>" />
	<?endif;?>
	<? if (!empty($pageDescription)):?>
		<meta name="description" content="<?=$pageDescription?>" />
	<?endif;?>
</head>
<body>
	<div class="container content-wrapper">
		<div class="row">
			<div class="right col-md-3">
				<a class="<?=$loginClass?>" href="javascript:void(0)"><?=$linkTitle?></a>
				<a class="sort desc" data-type="desc" href="#user_email">sort_by_email</a>
				<a class="sort desc" data-type="desc" href="#user_name">sort_by_user_name</a>
				<a class="sort desc" data-type="desc" href="#status_id">sort_by_status</a>
			</div>
			<?=$content?>
		</div>
		<div class="row">
			<div class="col-md-12">
				<? if (!empty($pagen)): ?>
					<?=$pagen?>
				<? endif; ?>
			</div>
		</div>
	</div>
</body>
</html>